version: '3'

vars:
  OUTPUT: openapi.generated.yaml

tasks:
  default:
    desc: Run the Telegram Bot API parser (prints OpenAPI to stdout)
    cmds:
      - go run ./cmd/tgbotspec

  parse:
    desc: Run the Telegram Bot API parser (prints OpenAPI to stdout)
    cmds:
      - go run ./cmd/tgbotspec

  parse:save:
    desc: Run the parser and save the generated OpenAPI to a file
    cmds:
      - go run ./cmd/tgbotspec > {{.OUTPUT}}

  validate:
    desc: Validate the generated OpenAPI spec using openapi-spec-validator
    cmds:
      - docker run --rm -v $(pwd)/{{.OUTPUT}}:/openapi.yaml pythonopenapi/openapi-spec-validator /openapi.yaml

  lint:
    desc: Run golangci-lint against the project
    cmds:
      - go tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint run ./...

  test:
    desc: Run go test with coverage and print the summary to the console
    cmds:
      - mkdir -p .cache/go-build
      - GOCACHE=$(pwd)/.cache/go-build go test -coverprofile=coverage.out -covermode=atomic ./...
      - GOCACHE=$(pwd)/.cache/go-build go tool cover -func=coverage.out
