version: '3'

tasks:
  generate:
    desc: Generate Telegram Bot API Go client
    dir: ../..
    cmds:
      - go run ./cmd/tgbotspec --merge-union-types > openapi.generated.yaml
      - go tool oapi-codegen -config tools/oapi-codegen/config.yaml openapi.generated.yaml
