version: '3'

tasks:
  generate:
    desc: Generate Telegram Bot API Go client
    dir: ../..
    cmds:
      - task parse:save
      - go tool oapi-codegen -config tools/oapi-codegen/config.yaml openapi.generated.yaml
