name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - feature/*
      - hotfix/*
      - bugfix/*
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic
      - name: Vulnerability check
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          go-package: ./...
      - name: Upload coverage reports to Codecov
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v6
        with:
          files: coverage.out
          fail_ci_if_error: false
          use_oidc: true
